// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVa6pksvQvzDEbLppMjL4yFYdI1iItOB8',
    appId: '1:460456572303:android:462a1bfec01e128aedc7fa',
    messagingSenderId: '460456572303',
    projectId: 'a-safe-place-fb',
    databaseURL: 'https://a-safe-place-fb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'a-safe-place-fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmaA6aFGzYVdF2rEpmSTnnYSIk1r7HV_A',
    appId: '1:460456572303:ios:c612e03a122af705edc7fa',
    messagingSenderId: '460456572303',
    projectId: 'a-safe-place-fb',
    databaseURL: 'https://a-safe-place-fb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'a-safe-place-fb.appspot.com',
    iosClientId: '460456572303-3hjb0r4bs6k6rlb7q1ttr4jiuvcqjb93.apps.googleusercontent.com',
    iosBundleId: 'com.example.aSafePlace',
  );
}
